name: Node.js CI

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Format
              run: npm run format --if-present

            - name: Lint
              run: npm run lint --if-present

            - name: Test
              run: npm test

        #   - name: Build
        #     run: npm run build --if-present
