name: Node.js CI

on:
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build For PR
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3

              with:
                  node-version: 18.x

            - name: Install dependencies
              run: npm install

            - name: Format
              run: npm run format --if-present

            - name: Lint
              run: npm run lint --if-present

            - name: Test
              run: npm test

        #   - name: Build
        #     run: npm run build --if-present
